name: Deploy Static HTML to cPanel

on:
  push:
    branches:
      - main # Cambia esta rama si es necesario

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to cPanel
      uses: samkirkland/ftp-deploy-action@v4.3.4
      with:
        server: 191.101.0.20
        username: lesinnovations@lesinnovations.tech
        password: kV,#.tNQ(RZ5
        local-dir: . # Directorio raíz de tu sitio en el repositorio
        server-dir: /lesinnovations.tech/ # Actualiza según tu estructura en cPanel
